package fsanalysis;

public class StockBasics {
    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double pe;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double outstanding;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double totals;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double totalassets;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double liquidassets;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double fixedassets;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double reserved;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double reservedpershare;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double esp;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double bvps;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double pb;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Long timetomarket;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double undp;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double perundp;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double rev;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double profit;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double gpr;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Double npr;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private Long holders;

    
    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private String code;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private String name;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private String industry;

    /**
     * 
     * This element is automatically generated by MyBatis Generator, do not modify. 
     *
     * @mbggenerated Wed Jan 25 17:07:54 CST 2017
     */
    private String area;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }
    public Double getPe() {
        return pe;
    }

    public void setPe(Double pe) {
        this.pe = pe;
    }

    public Double getOutstanding() {
        return outstanding;
    }

    public void setOutstanding(Double outstanding) {
        this.outstanding = outstanding;
    }

    public Double getTotals() {
        return totals;
    }

    public void setTotals(Double totals) {
        this.totals = totals;
    }

    public Double getTotalassets() {
        return totalassets;
    }

    public void setTotalassets(Double totalassets) {
        this.totalassets = totalassets;
    }

    public Double getLiquidassets() {
        return liquidassets;
    }

    public void setLiquidassets(Double liquidassets) {
        this.liquidassets = liquidassets;
    }

    public Double getFixedassets() {
        return fixedassets;
    }

    public void setFixedassets(Double fixedassets) {
        this.fixedassets = fixedassets;
    }

    public Double getReserved() {
        return reserved;
    }

    public void setReserved(Double reserved) {
        this.reserved = reserved;
    }

    public Double getReservedpershare() {
        return reservedpershare;
    }

    public void setReservedpershare(Double reservedpershare) {
        this.reservedpershare = reservedpershare;
    }

    public Double getEsp() {
        return esp;
    }

    public void setEsp(Double esp) {
        this.esp = esp;
    }

    public Double getBvps() {
        return bvps;
    }

    public void setBvps(Double bvps) {
        this.bvps = bvps;
    }

    public Double getPb() {
        return pb;
    }

    public void setPb(Double pb) {
        this.pb = pb;
    }

    public Long getTimetomarket() {
        return timetomarket;
    }

    public void setTimetomarket(Long timetomarket) {
        this.timetomarket = timetomarket;
    }

    public Double getUndp() {
        return undp;
    }

    public void setUndp(Double undp) {
        this.undp = undp;
    }

    public Double getPerundp() {
        return perundp;
    }

    public void setPerundp(Double perundp) {
        this.perundp = perundp;
    }

    public Double getRev() {
        return rev;
    }

    public void setRev(Double rev) {
        this.rev = rev;
    }

    public Double getProfit() {
        return profit;
    }

    public void setProfit(Double profit) {
        this.profit = profit;
    }

    public Double getGpr() {
        return gpr;
    }

    public void setGpr(Double gpr) {
        this.gpr = gpr;
    }

    public Double getNpr() {
        return npr;
    }

    public void setNpr(Double npr) {
        this.npr = npr;
    }

    public Long getHolders() {
        return holders;
    }

    public void setHolders(Long holders) {
        this.holders = holders;
    }
}